=== michael-n-cooper/recipes/recipes.dtd
<!ENTITY % URI "CDATA">
<!ENTITY % inline "em | reciperef">
<!ENTITY % step "quantity | ingredient | temperature | time | equipment | procedure">
<!ELEMENT recipe (title, meta?, ((group, group+, (steps | activity+)?) | (ingredients, (steps | activity+))), serving?, variation*, storage?)>
<!ATTLIST recipe
	photo %URI; #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT meta (source?, cuisine*, dishtype*, occasion*, comment*, processnote*)>
<!ELEMENT cuisine (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT dishtype (#PCDATA)>
<!ELEMENT occasion (#PCDATA)>
<!-- enrich with linking stuff -->
<!ELEMENT comment (#PCDATA | %inline;)*>
<!ELEMENT processnote (#PCDATA | %inline; | %step;)*>
<!ELEMENT group (label?, comment?, processnote?, ingredients, (steps | activity+)?)>
<!ELEMENT ingredients (yield?, (ingredient | ingredient_choice)+)>
<!ELEMENT yield (#PCDATA)>
<!-- enrich servings or quantity -->
<!ELEMENT ingredient ((range? | quantity*), variant?, item, preprep?, note?)>
<!ATTLIST ingredient
	mainingredient (true | false) "false"
	optional (true | false) "false"
>
<!ELEMENT range (quantity, quantity)>
<!ELEMENT quantity (value?, unit?, quantity*, altmeasure*)>
<!ATTLIST quantity
	approximate (true | false) "false"
>
<!-- deprecated: simply quantity inside quantity is alt measure -->
<!ELEMENT altmeasure (quantity+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT variant (#PCDATA)>
<!ELEMENT item (#PCDATA | reciperef)*>
<!-- enrich to reference database -->
<!ELEMENT preprep (#PCDATA)>
<!-- inline elements -->
<!ELEMENT note (#PCDATA | %inline;)*>
<!-- enrich to reference things like &quot;chopped&quot; -->
<!ELEMENT ingredient_choice ((ingredient | ingredient_group)*)>
<!ELEMENT ingredient_group (ingredient, ingredient+)>
<!ELEMENT steps (step+)>
<!ELEMENT step (#PCDATA | %step; | %inline;)*>
<!-- inline elements, quantities, temperatures, etc. -->
<!ATTLIST step
	photo %URI; #IMPLIED
>
<!ELEMENT activity (label, comment?, processnote?, (steps+ | activity+))>
<!ELEMENT label (#PCDATA)>
<!ELEMENT serving (#PCDATA | %step; | %inline;)*>
<!-- serving suggestions/instructions -->
<!ELEMENT variation (label?, comment?, processnote?, ingredients?, (steps+ | activity+))>
<!-- possibly same content model as step -->
<!ELEMENT storage (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ATTLIST temperature
	scale (Fahrenheit | Celsius) "Fahrenheit"
>
<!ELEMENT time (#PCDATA)>
<!-- equipment: oven, spatula, 9&quot; fry pan, etc. -->
<!ELEMENT equipment (#PCDATA)>
<!-- procedure: bake, stir-fry, etc. -->
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT reciperef (#PCDATA)>
<!ATTLIST reciperef
	ref CDATA #REQUIRED
>
<!ELEMENT em (#PCDATA)>

=== michael-n-cooper/recipes/source/french-crullers.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>French Crullers</title>
	<meta>
		<dishtype>Donuts</dishtype>
	</meta>
    <ingredients>
        <ingredient>
            <item>choux dough</item>
        </ingredient>
        <ingredient>
            <item>shortening for frying</item>
        </ingredient>
    </ingredients>
    <steps>
        <step>Prepare the choux dough.</step>
        <step>Put the dough in a <equipment>pastry bag</equipment> fitted with a <equipment>half-inch star tip</equipment>.</step>
        <step>Cut a few 10 cm squares of <equipment>parchment paper</equipment>.</step>
        <step>Add enough shortening to a pan or fryer to cover the donuts when melted (about 5 cm deep). Heat to <temperature>370</temperature>.</step>
        <step>Using <equipment>tongs</equipment>, dip the parchment squares in the oil and remove to a surface.</step>
        <step>Pipe circles of choux dough on the parchment squares.</step>
        <step>Gently set dough on their parchment in shortening a few at a time, leaving room for expansion. Remove the parchment with tongs to use for next set of donuts, and <procedure>deep fry</procedure> until light brown, about <time>1 minute</time>. Turn over, and fry until second side browns, another <time>1 minute</time>.</step>
        <step>Remove to the wire rack and let cool while frying the remainder.</step>
    </steps>
	<serving>Cool and cover on both sides with confectioners' sugar glaze.</serving>
	<storage>Donuts don't store well, but can be frozen. Freeze the day they are made.</storage>
</recipe>

=== michael-n-cooper/recipes/source/crumbpietopping.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Crumb Topping for Pie</title>
	<meta>
		<dishtype>Ingredients</dishtype>
		<dishtype>Pies</dishtype>
		<processnote>Use this in place of the top crust on a pie. The filling must be precooked before pouring into the shell.</processnote>
	</meta>
	<ingredients>
		<yield>Crust for one pie</yield>
		<ingredient>
			<quantity>
				<value>115</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>3/4</value>
						<unit>cup</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>flour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>155</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>3/4</value>
						<unit>cup</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2.5</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1/4</value>
						<unit>tsp</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1/2</value>
						<unit>tsp</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<variant>ground</variant>
			<item>cinnamon</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>80</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>6</value>
						<unit>tbs</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>butter</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Stir together the dry ingredients.</step>
		<step>Work in the butter until the mixture forms crumbs with pea-sized pieces.</step>
		<step>Fill pie with pre-cooked filling, and sprinkle crumbs evenly on top.</step>
		<step>Bake at <temperature>425</temperature> 15 minutes, then reduce heat to <temperature>350</temperature> and continue to bake until crust browns, approximately <time>25 minutes</time>.</step>
	</steps>
</recipe>

=== michael-n-cooper/recipes/source/buttermilkbiscuits.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Buttermilk Biscuits</title>
	<meta>
		<source>Marion Cunningham: The Fannie Farmer Cookbook, 13th Edition (1994: Knopf)</source>
		<cuisine>Southern</cuisine>
		<dishtype>Breads</dishtype>
		<dishtype>Rolls</dishtype>
		<comment>In my book, these are the only kind of biscuits to make. I use the American term "biscuits" though many of my friends know these as "scones".</comment>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>cups</unit>
			</quantity>
			<item>all-purpose flour</item>
			<note>This recipe calls for all-purpose flour. Low-protein cake or pastry flour is very good and more authentic, but make sure to use the same <em>weight</em> of flour, not the same volume. 2 cups of all-purpose flour is 10 ounces; this may be nearly 3 cups of pastry flour.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tsp</unit>
			</quantity>
			<item>baking powder</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/3</value>
				<unit>tsp</unit>
			</quantity>
			<item>baking soda</item>
			<note>Use a scant 1/2 tsp, as a full 1/2 tsp is too much and creates brown flecks.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>tbs</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>cup</unit>
				<altmeasure>
					<quantity>
						<value>4</value>
						<unit>oz</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>butter, shortening, or lard</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2/3</value>
				<unit>cup</unit>
			</quantity>
			<item>buttermilk</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Preheat oven to <temperature>425</temperature>.</step>
		<step>Stir together all the dry ingredients until well blended.</step>
		<step><procedure>Cut in the fat</procedure> until mixture resembles cornmeal.</step>
		<step>Add the buttermilk and mix until just blended.</step>
		<step>Knead 30 seconds on a floured board. The light kneading builds enough structure to help increase the rise. The buttermilk helps them remain tender.</step>
		<step>Pat or roll on board until 1/2 inch thick.</step>
		<step>Cut into 2-inch rounds. Place touching each other in 2 greased <equipment>8-inch round pans</equipment>.</step>
		<step>Optional: brush tops with melted butter.</step>
		<step>Bake <time>15-20 minutes</time>, until golden on top.</step>
	</steps>
	<variation>
	<label>Drop biscuits</label>
	<steps>
		<step>Use 
		<ingredient><quantity>
			<value>1</value>
			<unit>cup</unit>
		</quantity><item>buttermilk</item></ingredient>.</step>
		<step>Drop in spoonfuls onto baking sheet.</step>
	</steps>
</variation>
</recipe>

=== michael-n-cooper/recipes/source/bakedbeans.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Baked Beans</title>
	<meta>
		<source>Marion Cunningham: The Fannie Farmer Cookbook, 13th Edition (1994: Knopf)</source>
		<dishtype>Sides</dishtype>
	</meta>
	<ingredients>
		<ingredient mainingredient="true">
			<quantity>
				<value>1</value>
				<unit>lb</unit>
			</quantity>
			<item>white beans</item>
			<preprep> </preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
			<preprep> </preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>lb</unit>
			</quantity>
			<item>salt pork</item>
			<preprep> </preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tsp</unit>
			</quantity>
			<item>mustard powder</item>
			<preprep> </preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>5</value>
				<unit>tbs</unit>
			</quantity>
			<item>dark brown sugar</item>
			<preprep> </preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>4</value>
				<unit>tbs</unit>
			</quantity>
			<item>light molasses</item>
			<preprep> </preprep>
		</ingredient>
	</ingredients>
	<steps>
		<step>Soak the beans at least <time>8 hours</time> in twice the volume of water.</step>
		<step>Add salt, stir, then drain, reserving liquid.</step>
		<step>Preheat oven to <temperature>300</temperature>.</step>
		<step>Cut of 1/3 of the salt pork and place in bottom of a bean pot, then cover with the beans.</step>
		<step>Blend mustard, sugar, and molasses with reserved bean liquid, then pour over beans.</step>
		<step>Cut several gashes in remaining piece of salt pork (or cube it) and place on top of the beans.</step>
		<step>Cover and bake for <time>6 hours</time>, adding boiling water as needed to just cover the beans. Uncover for final hour to crisp salt pork. Correct seasoning before serving.</step>
	</steps>
</recipe>

=== michael-n-cooper/recipes/source/decoratingfrosting.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Decorating Frosting</title>
	<meta>
		<dishtype>Frostings</dishtype>
		<comment>A frosting that keeps its shape well for decorating cakes. It's a bit of a compromise among various attributes to work well for decorating, so I only use it when actually doing elaborate decorations.</comment>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>lb</unit>
			</quantity>
			<item>vegetable shortening</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>tsp</unit>
			</quantity>
			<variant>clear</variant>
			<item>vanilla extract</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<variant>artificial</variant>
			<item>almond extract</item>
			<note>I use artificial almond extract to eliminate concerns with nut allergies.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>tsp</unit>
			</quantity>
			<item>butter flavour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/8</value>
				<unit>tsp</unit>
			</quantity>
			<item>orange extract</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/8</value>
				<unit>tsp</unit>
			</quantity>
			<item>rose water</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/8</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>kg</unit>
			</quantity>
			<item>powdered sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>cup</unit>
			</quantity>
			<item>water</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tbs</unit>
			</quantity>
			<item>meringue powder</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Cream the shortening at medium high speed (setting 6 on the stand mixer) for 10 minutes. It will become smooth and fluffy.</step>
		<step>Gently incorporate the flavourings and salt.</step>
		<step>Sift together the icing sugar and meringue powder. Add cup by cup to the shortening, incorporating fully at low speed before adding more.</step>
		<step>Add some of the water as needed while adding the sugar to maintain a texture that can be mixed. All the sugar and water should be added by the end.</step>
		<step>Beat slowly 5 minutes more. Mix together gently until evenly blended. Don't whip too fast as that will incorporate air bubbles.</step>
	</steps>
	<serving>This is a thick consistency for decorations. Add small amounts of water to thin some of the batch for spreading.</serving>
	<storage>Store covered in the refrigerator 2 weeks, or in the freezer 3 months.</storage>
</recipe>

=== michael-n-cooper/recipes/source/holland-cream.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Holland Cream</title>
	<meta>
        <source>http://allrecipes.com/recipe/holland-cream-white-cream-filling/</source>
		<dishtype>Fillings</dishtype>
		<comment>This is the white creme filling in donuts. I love it with a chocolate icing. I don't know where the name comes from, but the recipes online, which all seem to be copies of each other, all call it that.</comment>
	</meta>
	<ingredients>
		<ingredient>
            <quantity>
                <value>225</value>
                <unit>g</unit>
                <altmeasure>
                    <quantity>
                        <value>1</value>
                        <unit>cup</unit>
                    </quantity>
                </altmeasure>
            </quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
            <quantity>
                <value>100</value>
                <unit>g</unit>
                <altmeasure>
                    <quantity>
                        <value>1/2</value>
                        <unit>cup</unit>
                    </quantity>
                </altmeasure>
            </quantity>
			<item>water</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>200</value>
				<unit>g</unit>
                <altmeasure>
                    <quantity>
                        <value>1</value>
                        <unit>cup</unit>
                    </quantity>
                </altmeasure>
			</quantity>
			<item>vegetable oil</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>360</value>
				<unit>g</unit>
                <altmeasure>
                    <quantity>
                        <value>2</value>
                        <unit>cups</unit>
                    </quantity>
                </altmeasure>
			</quantity>
			<item>vegetable shortening</item>
		</ingredient>
        <ingredient>
            <quantity>
                <value>1</value>
                <unit>tsp</unit>
            </quantity>
            <item>clear vanilla extract</item>
        </ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>kg</unit>
                <altmeasure>
                    <quantity>
                        <value>8</value>
                        <unit>cups</unit>
                    </quantity>
                </altmeasure>
			</quantity>
			<item>confectioners' sugar</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Put the white sugar and water in a <equipment>saucepan</equipment>. Put on medium heat and bring to a boil, stirring until the sugar has dissolved.</step>
		<step>Remove from heat, pour the syrup into a large mixing bowl, and let cool completely.</step>
		<step>Add vegetable oil, shortening, and clear vanilla extract, and beat with an electric mixer on high speed to blend.</step>
		<step>Add the confectioners' sugar 1 cup at a time and beat in. Continue to beat until the filling is thick and fluffy. If it's too thick, beat in a tablespoon of water at a time until it's the correct consistency.</step>
	</steps>
</recipe>

=== michael-n-cooper/recipes/source/bay-liqueur.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Bay Liqueur</title>
	<meta>
		<source>http://ecucinando.it/forum/rosolio-di-alloro-t8881.html</source>
		<dishtype>Liqueurs</dishtype>
		<comment>I encountered Bay Rosolio in Venice where it was served in chocolate cups. I was entranced by the unusual herbaceous flavour. They gave me a bottle but I have not been able to find it anywhere since, including in Venice. Perhaps this is because Rosolio (normally made with Rose petals) is a Sicilian specialty and is not widely available elsewhere. I finally found this recipe online to make my own, renamed to avoid brand confusion.</comment>
	</meta>
	<ingredients>
		<yield>1 Litre</yield>
		<ingredient>
			<quantity>
				<value>500</value>
				<unit>ml</unit>
				<altmeasure>
					<quantity>
						<value>400</value>
						<unit>g</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>95% ethyl alcohol</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>30</value>
				<altmeasure>
					<quantity>
						<value>20</value>
						<unit>g</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<variant>fresh</variant>
			<item>bay leaves</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3</value>
				<altmeasure>
					<quantity>
						<value>200</value>
						<unit>mg</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>cloves</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<altmeasure>
					<quantity>
						<value>2.5</value>
						<unit>g</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>cinnamon stick</item>
		</ingredient>
		<!--
		<ingredient optional="true">
			<quantity>
				<value>1</value>
				<unit>tsp</unit>
			</quantity>
			<item>fennel seeds</item>
			<note>for a more anise flavour</note>
		</ingredient>
		-->
		<ingredient>
			<quantity>
				<value>600</value>
				<unit>ml</unit>
				<altmeasure>
					<quantity>
						<value>600</value>
						<unit>g</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<variant>distilled</variant>
			<item>water</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>400</value>
				<unit>g</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Put the alcohol in a <equipment>500 mL jar</equipment> that can be sealed.</step>
		<step>Add the herbs and spices, seal, and <procedure>macerate</procedure> <time>2 weeks</time>. Alcohol will turn dark green and bay leaves will completely lose their colour.</step>
		<step>Combine sugar and water and bring to boil, stirring, until sugar dissolves. Cool.</step>
		<step>Strain the alcohol into the sugar syrup and mix together well.</step>
		<step>Filter into a <equipment>1 L jar</equipment>. Seal and put in a dark place for <time>1 week</time> undisturbed to allow sediment to precipitate.</step>
		<step><procedure>Filter</procedure> through a coffee filter.</step>
        <step>Transfer to a <equipment>1 L bottle</equipment> and close.</step>
	</steps>
	<storage>Store in a dark place up to 3 years.</storage>
</recipe>

=== michael-n-cooper/recipes/source/wholewheatbread-freshmilled.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Whole Wheat Sandwich Bread (made with home milled flour)</title>
	<meta>
		<dishtype>Breads</dishtype>
		<comment>Home milled flour allows an absolutely fresh and natural product. Because it is not subjected to commercial treatments, however, it's a little trickier to produce a nice, soft sandwich loaf. This recipe uses an autolyse period to help the more coarsely ground flour absorb liquid fully and begin gluten development, and ascorbic acid, which improves gluten formation and elasticity, to compensate for the fact that the flour wasn't aged.</comment>
	</meta>
	<ingredients>
		<yield>2 loaves</yield>
		<ingredient>
			<quantity>
				<value>640</value>
				<unit>ml</unit>
                <altmeasure>
                    <quantity>
                        <value>640</value>
                        <unit>ml</unit>
                    </quantity>
                </altmeasure>
			</quantity>
			<item>milk</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tbs</unit>
			</quantity>
			<item>butter</item>
			<preprep>softened</preprep>
		</ingredient>
		<ingredient mainingredient="true">
			<quantity>
				<value>910</value>
				<unit>g</unit>
				<altmeasure>
					<quantity approximate="true">
						<value>7</value>
						<unit>cups</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<variant>whole wheat</variant>
			<item>flour</item>
			<preprep>freshly milled</preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>pinch</unit>
			</quantity>
			<item>ascorbic acid</item>
		</ingredient>
		<ingredient optional="true">
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>diastatic malt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tbs</unit>
			</quantity>
			<item>honey</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tsp</unit>
			</quantity>
			<variant>instant</variant>
			<item>yeast</item>
		</ingredient>
	</ingredients>
	<steps>
		<step><procedure>Scald</procedure> the milk. Add butter and allow to cool to lukewarm (<temperature>110</temperature>).</step>
		<step>Stir the ascorbic acid and diastatic malt into the flour.</step>
        <step>Combine the milk and flour mixtures and stir together until a rough dough forms with no unincorporated flour.</step>
        <step>Cover and let rest (<procedure>autolyse</procedure>) for <time>20 minutes</time>.</step>
		<step>Sprinkle the honey, yeast, and salt over the bread and mix in.</step>
		<step><procedure>Knead</procedure> about <time>10 minutes</time> (or <time>5 minutes</time> in a mixer), until dough is supple, elastic, bounces back when pressed, and passes a <procedure>windowpane test</procedure>. This dough is somewhat soft and slightly sticky because it has more liquid than most sandwich breads, which the bran absorbs.</step>
		<step>Add about 1/2 tsp oil to a clean bowl that is at least three times the volume of the dough. Form dough into a ball and place upside down in the bowl, coat with the oil, then flip dough over to coat the underside.</step>
        <step>Cover bowl and let dough <procedure>ferment</procedure>. Dough should rise to about 2 1/2 times its original volume. It should still have a domed top but should not spring back much when pressed. This usually takes about <time>2 to 3 hours</time>, depending on temperature.</step>
		<step>Turn out of bowl, divide in half, and form each half into a ball. Let rest a few minutes.</step>
		<step>Shape each ball into a pan loaf by patting out into a circle, then folding two sides into the center and pinching together along most of the length, then folding in the ends and pinching in a triangular pattern from the original seam to seal everything together.</step>
		<step>Grease two <equipment>8 1/2 by 4 1/2 inch loaf pans</equipment> and place each loaf in one, seam side down.</step>
        <step>Cover with plastic or a towel and let <procedure>proof</procedure> until just under doubled in bulk. This rising will take slightly less than half the time the first rising took, and the dough will feel soft when gently touched but still slightly springy.</step>
		<step>About 10 minutes before the dough is finished rising, preheat the oven to <temperature>375</temperature>.</step>
        <step>When the dough is ready, put in the oven. Do not open the oven door while it bakes. Bake about <time>50 minutes</time>, until crust is browned and feels solid to the touch.</step>
		<step>Take bread out of the oven, remove from the pan, and cool completely on a rack before slicing.</step>
	</steps>
	<storage>Store in plastic bread bags a couple days. Bread can be frozen without much impact on quality; slice it first and take out only the slices needed, which should be thawed in a microwave. Do not refrigerate bread, this accelerates staling.</storage>
</recipe>
