=== michael-n-cooper/recipes/recipes.dtd
<!ENTITY % URI "CDATA">
<!ENTITY % inline "em | reciperef">
<!ENTITY % step "quantity | ingredient | temperature | time | equipment | procedure">
<!ELEMENT recipe (title, meta?, ((group, group+, (steps | activity+)?) | (ingredients, (steps | activity+))), serving?, variation*, storage?)>
<!ATTLIST recipe
	photo %URI; #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT meta (source?, cuisine*, dishtype*, occasion*, comment*, processnote*)>
<!ELEMENT cuisine (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT dishtype (#PCDATA)>
<!ELEMENT occasion (#PCDATA)>
<!-- enrich with linking stuff -->
<!ELEMENT comment (#PCDATA | %inline;)*>
<!ELEMENT processnote (#PCDATA | %inline; | %step;)*>
<!ELEMENT group (label?, comment?, processnote?, ingredients, (steps | activity+)?)>
<!ELEMENT ingredients (yield?, (ingredient | ingredient_choice)+)>
<!ELEMENT yield (#PCDATA)>
<!-- enrich servings or quantity -->
<!ELEMENT ingredient ((range? | quantity*), variant?, item, preprep?, note?)>
<!ATTLIST ingredient
	mainingredient (true | false) "false"
	optional (true | false) "false"
>
<!ELEMENT range (quantity, quantity)>
<!ELEMENT quantity (value?, unit?, quantity*, altmeasure*)>
<!ATTLIST quantity
	approximate (true | false) "false"
>
<!-- deprecated: simply quantity inside quantity is alt measure -->
<!ELEMENT altmeasure (quantity+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT variant (#PCDATA)>
<!ELEMENT item (#PCDATA | reciperef)*>
<!-- enrich to reference database -->
<!ELEMENT preprep (#PCDATA)>
<!-- inline elements -->
<!ELEMENT note (#PCDATA | %inline;)*>
<!-- enrich to reference things like &quot;chopped&quot; -->
<!ELEMENT ingredient_choice ((ingredient | ingredient_group)*)>
<!ELEMENT ingredient_group (ingredient, ingredient+)>
<!ELEMENT steps (step+)>
<!ELEMENT step (#PCDATA | %step; | %inline;)*>
<!-- inline elements, quantities, temperatures, etc. -->
<!ATTLIST step
	photo %URI; #IMPLIED
>
<!ELEMENT activity (label, comment?, processnote?, (steps+ | activity+))>
<!ELEMENT label (#PCDATA)>
<!ELEMENT serving (#PCDATA | %step; | %inline;)*>
<!-- serving suggestions/instructions -->
<!ELEMENT variation (label?, comment?, processnote?, ingredients?, (steps+ | activity+))>
<!-- possibly same content model as step -->
<!ELEMENT storage (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ATTLIST temperature
	scale (Fahrenheit | Celsius) "Fahrenheit"
>
<!ELEMENT time (#PCDATA)>
<!-- equipment: oven, spatula, 9&quot; fry pan, etc. -->
<!ELEMENT equipment (#PCDATA)>
<!-- procedure: bake, stir-fry, etc. -->
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT reciperef (#PCDATA)>
<!ATTLIST reciperef
	ref CDATA #REQUIRED
>
<!ELEMENT em (#PCDATA)>

=== michael-n-cooper/recipes/source/eggnog.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Eggnog</title>
	<meta>
		<dishtype>Beverages</dishtype>
		<comment>This appears to be a pretty traditional eggnog, I'm recording it here mainly for the proportions I like.</comment>
	</meta>
	<ingredients>
		<yield>12 servings</yield>
		<ingredient>
			<quantity>
				<value>6</value>
			</quantity>
			<item>eggs</item>
			<preprep>separated</preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/8</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3/4</value>
				<unit>cup</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>Dark rum or brandy</item>
			<note>This can be any non-flavoured 40-proof spirit. Rum, brandy, bourbon, and whisky are traditional, depending on who you ask. Many recipes call for mostly brandy or bourbon and a bit of rum.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>4</value>
				<unit>cups</unit>
			</quantity>
			<item>milk</item>
			<note>This is probably meant to be whole milk. For best results, substitute an appropriate amount of cream to yield the butterfat content of whole milk.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>tsp</unit>
			</quantity>
			<item>vanilla extract</item>
		</ingredient>
		<ingredient_choice>
			<ingredient>
				<quantity>
					<value>1/2</value>
					<unit>tsp</unit>
				</quantity>
				<item>nutmeg</item>
				<preprep>ground</preprep>
			</ingredient>
			<ingredient>
				<quantity>
					<value>1/8</value>
					<unit>tsp</unit>
				</quantity>
				<item>mace</item>
			</ingredient>
		</ingredient_choice>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>cup</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<variant>whipping</variant>
			<item>cream</item>
		</ingredient>
		<ingredient>
			<item>nutmeg</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Beat egg yolks with salt and 1/2 cup sugar until they form a ribbon.</step>
		<step>Slowly beat in the spirit, then the milk. Slow the beater as it becomes more liquid, to avoid splashing. Add vanilla and nutmeg.</step>
		<step>Refrigerate overnight in a sealed container to let flavours blend and mature.</step>
		<step>Just before serving, whip the egg whites with the 1/4 cup  sugar until stiff and fold into the milk mixture. Whip the cream until stiff and fold it into the mixture.</step>
	</steps>
	<serving>Serve in a punch bowl. Ladle into cups and grate a small sprinkle of nutmeg on top. The nutmeg is important as the aroma accentuates the flavour when drinking.</serving>
</recipe>

=== michael-n-cooper/recipes/source/chocolatefrosting.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Chocolate Frosting</title>
	<meta>
		<source>Cook's Country</source>
		<dishtype>Frostings</dishtype>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>4</value>
				<unit>tbs</unit>
			</quantity>
			<variant>unsalted</variant>
			<item>butter</item>
			<preprep>cut into 4 pieces</preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>oz</unit>
			</quantity>
			<variant>unsweetened</variant>
			<item>chocolate</item>
			<preprep>chopped</preprep>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3/4</value>
				<unit>cup</unit>
			</quantity>
			<item>cocoa</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3</value>
				<unit>cups</unit>
			</quantity>
			<item>powdered sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>cup</unit>
			</quantity>
			<item>milk</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Melt butter and chocolate together until smooth. Stir in salt and cool <time>10 minutes</time>.</step>
		<step>Sift together cocoa and powdered sugar.</step>
		<step>Gradually add cocoa mixture to chocolate mixture, beating constantly at low speed.</step>
		<step>Gradually add milk, beating until completely incorporated.</step>
		<step>Beat at high speed until light and creamy, about <time>1 minute</time>.</step>
	</steps>
</recipe>

=== michael-n-cooper/recipes/source/gooseberry-jam.en.xml
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
    <title>Gooseberry Jam</title>
    <meta>
        <dishtype>Jams</dishtype>
        <processnote>Gooseberry jam is tart and flavourful, good on scones to accompany meats.</processnote>
    </meta>
    <ingredients>
        <yield>3 pints</yield>
        <ingredient>
            <quantity>
                <value>1000</value>
                <unit>g</unit>
            </quantity>
            <item>gooseberries</item>
        </ingredient>
        <ingredient>
            <quantity>
                <value>250</value>
                <unit>g</unit>
            </quantity>
            <item>water</item>
        </ingredient>
        <ingredient>
            <quantity>
                <value>1000</value>
                <unit>g</unit>
            </quantity>
            <item>sugar</item>
        </ingredient>
    </ingredients>
    <steps>
        <step>Fill a canning kettle with water to the appropriate level and bring to boil. Reduce heat and keep ready at the boil until the jam is ready. Sterilize <equipment>canning jars</equipment> and lids.</step>
        <step>Pick over the gooseberries to remove stems and leaves, and rinse them.</step>
        <step>Put the gooseberries and water in a pot with at least three times the capacity of the batch.</step>
        <step>Bring batch to a boil. Keep at the boil, stirring occasionally, until the gooseberries soften and begin to break down, the volume drops noticeably, and mixture starts to thicken.</step>
        <step>Add the sugar to the gooseberries, stir in to dissolve, and return to the boil. Continue to cook, stirring frequently, until the batch reaches the jellying point, around <temperature>221</temperature>.</step>
        <step><procedure>Can</procedure> and seal jars in canning kettle <time>10 minutes</time>.</step>
    </steps>
</recipe>

=== michael-n-cooper/recipes/source/cheesesauce.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Cheese Sauce</title>
	<meta>
		<dishtype>Ingredients</dishtype>
		<dishtype>Sauces, Marinades, Dressings</dishtype>
		<comment>This is a bulk preparation of cheese sauce, primarily for macaroni and cheese (just mix into cooked noodles and heat) but also good on vegetables.</comment>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>4</value>
				<unit>tbs</unit>
			</quantity>
			<item>butter</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/3</value>
				<unit>cup</unit>
			</quantity>
			<item>flour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3</value>
				<unit>cups</unit>
			</quantity>
			<item>milk</item>
		</ingredient>
		<ingredient mainingredient="true">
			<quantity>
				<value>12</value>
				<unit>oz</unit>
			</quantity>
			<item>cheddar cheese</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>paprika</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>dash</unit>
			</quantity>
			<item>cayenne</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Melt the butter over medium heat. Whisk in the flour. Cook, whisking constantly, a few minutes until foaming subsides and the roux seems to become more liquid.</step>
		<step>Add the milk all at once, whisking rapidly. Continue whisking while the milk heats up and the sauce thickens.</step>
		<step>Add the remaining ingredients. Continue to blend until the cheese is completely melted.</step>
	</steps>
	<storage>Store in the refrigerator up to 2 weeks.</storage>
</recipe>

=== michael-n-cooper/recipes/source/shortbread-cookies.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Shortbread Cookies</title>
	<meta>
		<dishtype>Desserts</dishtype>
		<dishtype>Cookies</dishtype>
	</meta>
	<ingredients>
		<ingredient mainingredient="true">
			<quantity>
				<value>350</value>
				<unit>g</unit>
				<quantity>
					<value>1 1/2</value>
					<unit>cup</unit>
				</quantity>
				<quantity>
					<value>3</value>
					<unit>sticks</unit>
				</quantity>
			</quantity>
			<item>butter</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>200</value>
				<unit>g</unit>
				<quantity>
					<value>1</value>
					<unit>cup</unit>
				</quantity>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<quantity>
					<value>57</value>
					<unit>g</unit>
				</quantity>
			</quantity>
			<item>egg</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>25</value>
				<unit>g</unit>
				<quantity>
					<value>2</value>
					<unit>tbs</unit>
				</quantity>
			</quantity>
			<item>milk</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>tsp</unit>
			</quantity>
			<item>vanilla extract</item>
		</ingredient>
		<ingredient optional="true">
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>almond extract</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>400</value>
				<unit>g</unit>
				<quantity>
					<value>2 3/4</value>
					<unit>cups</unit>
				</quantity>
			</quantity>
			<item>flour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
				<unit>tsp</unit>
			</quantity>
			<item>baking powder</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Preheat oven to <temperature>350</temperature>.</step>
		<step><procedure>Cream</procedure> butter and sugar together.</step>
		<step>Add egg, milk, and extracts and mix until smooth.</step>
		<step><procedure>Sift</procedure> together flour, baking powder, and salt, then stir into butter mixture.</step>
		<step>Form into 1-tbs balls and place on cookie sheet about 2.5 cm apart, then flatten.</step>
		<step>Bake about <time>10 minutes</time>, until they begin to turn light brown at edges.</step>
		<step>Cool on sheet <time>1 minute</time>, then slide off cookie sheet.</step>
	</steps>
	<variation>
		<label>Spritz cookies</label>
		<steps>
			<step>Set oven to <temperature>400</temperature>.</step>
			<step>Put finished dough in a <equipment>cookie press</equipment>.</step>
			<step>Press cookies on ungreased and unlined cookie sheets, as close together as possible.</step>
		</steps>
	</variation>
	<variation>
		<label>Jam tots</label>
		<steps>
			<step>Instead of flattening the balls, use the thumb or a wine cork to make a hole in the center, almost to the bottom.</step>
			<step>Bake <time>8 minutes</time>. Remove from oven, remake the impressions with a larger tool, then return to oven and bake <time>5 minutes</time> longer.</step>
			<step>After cookies have cooled, melt jelly or strained jam. Carefully spoon into the impressions to the very brim, about 1 tsp per cookie.</step>
			<step>Let sit <time>a few days</time> for the jelly to set and shrink down a little.</step>
		</steps>
	</variation>
	<storage>Store tightly covered up to 1 week. Freeze for longer storage.</storage>
</recipe>

=== michael-n-cooper/recipes/source/cranberrysauce.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Cranberry Sauce</title>
	<meta>
		<dishtype>Sauces, Marinades, Dressings</dishtype>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>water</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/16</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>16</value>
				<unit>oz</unit>
			</quantity>
			<variant>whole fresh or frozen</variant>
			<item>cranberries</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Bring water, sugar, and salt to a boil.</step>
		<step>Stir in cranberries and return to the boil, stirring.</step>
		<step>Reduce heat and continue to cook <time>5 minutes</time>, stirring occasionally.</step>
	</steps>
	<serving>Let cool before serving.</serving>
	<storage>Store covered in the refrigerator.</storage>
</recipe>

=== michael-n-cooper/recipes/source/chocolate-icing.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Chocolate Icing</title>
	<meta>
		<dishtype>Icing</dishtype>
		<comment>This is a simple chocolate icing with an assertive flavour.</comment>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>50</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1/4</value>
						<unit>cup</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>milk</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>100</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1</value>
						<unit>cups</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>50</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>4</value>
						<unit>tbs</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>butter</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>100</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>2</value>
						<unit>cups</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>confectioner's sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>50</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1/2</value>
						<unit>cup</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>cocoa powder</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2.5</value>
				<unit>g</unit>
				<altmeasure>
					<quantity>
						<value>1/2</value>
						<unit>tsp</unit>
					</quantity>
				</altmeasure>
			</quantity>
			<item>vanilla extract</item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Combine milk and sugar in a pot and heat, stirring frequently, until sugar dissolves.</step>
		<step>Add butter and allow to melt.</step>
		<step>Add remaining ingredients and beat until smooth.</step>
		<step>Correct thickness by adding more sugar or milk if needed.</step>
	</steps>
	<serving>Warm icing slightly over hot water to increase fluidity. Dip pastries into icing and let dry.</serving>
</recipe>

=== michael-n-cooper/recipes/source/coffeecakequick.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Quick Coffee Cake</title>
	<meta>
		<source>Joy of Cooking</source>
		<dishtype>Breakfast</dishtype>
		<occasion>Sunday Brunch</occasion>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>flour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>baking soda</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>cup</unit>
			</quantity>
			<item>butter</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/4</value>
				<unit>cup</unit>
			</quantity>
			<item>sugar</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1</value>
			</quantity>
			<item>egg</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2/3</value>
				<unit>cup</unit>
			</quantity>
			<item>buttermilk</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>vanilla extract</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>cup</unit>
			</quantity>
			<item><reciperef ref="streusel">streusel</reciperef></item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Sift together the flour, salt, and baking soda.</step>
		<step>Cream the butter, then cream in the sugar and beat until fluffy.</step>
		<step>Add the egg and beat well, then stir in the buttermilk.</step>
		<step>Stir in the flour mixture until just blended.</step>
		<step>Spread in a <equipment>9-inch square pan</equipment>. Sprinkle evenly with streusel.</step>
		<step>Bake at <temperature>350</temperature>F for about <time>30 minutes</time>, until brown and done inside. Cool on a rack.</step>
	</steps>
</recipe>
