=== michael-n-cooper/recipes/recipes.dtd
<!ENTITY % URI "CDATA">
<!ENTITY % inline "em | reciperef">
<!ENTITY % step "quantity | ingredient | temperature | time | equipment | procedure">
<!ELEMENT recipe (title, meta?, ((group, group+, (steps | activity+)?) | (ingredients, (steps | activity+))), serving?, variation*, storage?)>
<!ATTLIST recipe
	photo %URI; #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT meta (source?, cuisine*, dishtype*, occasion*, comment*, processnote*)>
<!ELEMENT cuisine (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT dishtype (#PCDATA)>
<!ELEMENT occasion (#PCDATA)>
<!-- enrich with linking stuff -->
<!ELEMENT comment (#PCDATA | %inline;)*>
<!ELEMENT processnote (#PCDATA | %inline; | %step;)*>
<!ELEMENT group (label?, comment?, processnote?, ingredients, (steps | activity+)?)>
<!ELEMENT ingredients (yield?, (ingredient | ingredient_choice)+)>
<!ELEMENT yield (#PCDATA)>
<!-- enrich servings or quantity -->
<!ELEMENT ingredient ((range? | quantity*), variant?, item, preprep?, note?)>
<!ATTLIST ingredient
	mainingredient (true | false) "false"
	optional (true | false) "false"
>
<!ELEMENT range (quantity, quantity)>
<!ELEMENT quantity (value?, unit?, quantity*, altmeasure*)>
<!ATTLIST quantity
	approximate (true | false) "false"
>
<!-- deprecated: simply quantity inside quantity is alt measure -->
<!ELEMENT altmeasure (quantity+)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT variant (#PCDATA)>
<!ELEMENT item (#PCDATA | reciperef)*>
<!-- enrich to reference database -->
<!ELEMENT preprep (#PCDATA)>
<!-- inline elements -->
<!ELEMENT note (#PCDATA | %inline;)*>
<!-- enrich to reference things like &quot;chopped&quot; -->
<!ELEMENT ingredient_choice ((ingredient | ingredient_group)*)>
<!ELEMENT ingredient_group (ingredient, ingredient+)>
<!ELEMENT steps (step+)>
<!ELEMENT step (#PCDATA | %step; | %inline;)*>
<!-- inline elements, quantities, temperatures, etc. -->
<!ATTLIST step
	photo %URI; #IMPLIED
>
<!ELEMENT activity (label, comment?, processnote?, (steps+ | activity+))>
<!ELEMENT label (#PCDATA)>
<!ELEMENT serving (#PCDATA | %step; | %inline;)*>
<!-- serving suggestions/instructions -->
<!ELEMENT variation (label?, comment?, processnote?, ingredients?, (steps+ | activity+))>
<!-- possibly same content model as step -->
<!ELEMENT storage (#PCDATA)>
<!ELEMENT temperature (#PCDATA)>
<!ATTLIST temperature
	scale (Fahrenheit | Celsius) "Fahrenheit"
>
<!ELEMENT time (#PCDATA)>
<!-- equipment: oven, spatula, 9&quot; fry pan, etc. -->
<!ELEMENT equipment (#PCDATA)>
<!-- procedure: bake, stir-fry, etc. -->
<!ELEMENT procedure (#PCDATA)>
<!ELEMENT reciperef (#PCDATA)>
<!ATTLIST reciperef
	ref CDATA #REQUIRED
>
<!ELEMENT em (#PCDATA)>

=== michael-n-cooper/recipes/source/brownies.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Brownies</title>
	<meta>
		<source>Marion Cunningham: The Fannie Farmer Cookbook, 13th Edition (1994: Knopf)</source>
		<dishtype>Desserts</dishtype>
	</meta>
	<ingredients>
		<ingredient mainingredient="true">
			<quantity>
				<value>6</value>
				<unit>oz</unit>
			</quantity>
			<variant>unsweetened</variant>
			<item>chocolate</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>3/4</value>
				<unit>cup</unit>
			</quantity>
			<item>butter</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>4</value>
			</quantity>
			<item>eggs</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2</value>
				<unit>tbs</unit>
			</quantity>
			<item>vanilla extract</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1/2</value>
				<unit>tsp</unit>
			</quantity>
			<item>salt</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>2 3/4</value>
				<unit>cups</unit>
			</quantity>
			<item>sugar</item>
			<note>Fine crystal sugar is best as it dissolves more easily into the eggs.</note>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>flour</item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item>walnuts</item>
			<preprep>chopped</preprep>
		</ingredient>
	</ingredients>
	<steps>
		<step>Toast the walnuts about <time>15 minutes</time> in a <temperature>350</temperature> oven until fragrant. Cool. Increase oven heat to <temperature>375</temperature>. Butter and flour a <equipment>9 x 13 x 2 inch baking pan</equipment>.</step>
		<step>Melt chocolate and butter together, stirring often. Remove from heat and cool.</step>
		<step>Combine the eggs, vanilla, salt, and sugar in a mixing bowl and <procedure>beat</procedure> for <time>8 to 10 minutes</time>, until light in colour, fluffy, and the sugar has dissolved.</step>
		<step>Gently stir in the chocolate and butter mixture, then fold in the flour just until well blended. Stir in the walnuts.</step>
		<step>Spread in the prepared baking pan and bake about <time>25 minutes</time>, until the edges are set but the center is still slightly moist.</step>
		<step>Cool in the pan a few hours, then cut into squares.</step>
	</steps>
</recipe>

=== michael-n-cooper/recipes/source/custard-apple-tart.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Custard Apple Tart</title>
	<meta>
		<cuisine>French</cuisine>
		<dishtype>Tarts</dishtype>
	</meta>
	<group>
		<label>Shell</label>
		<ingredients>
            <ingredient>
                <quantity>
                    <value>100</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>3/4</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <variant>all-purpose</variant>
                <item>flour</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>100</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>3/4</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <variant>pastry</variant>
                <item>flour</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>25</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>2</value>
                            <unit>tbs</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>sugar</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>3</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/2</value>
                            <unit>tsp</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>salt</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>150</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>12</value>
                            <unit>tbs</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>butter</item>
            </ingredient>
            <ingredient>
                <quantity approximate="true">
                    <value>75</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/3</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>water</item>
                <preprep>ice cold</preprep>
            </ingredient>
		</ingredients>
		<steps>
			<step>Add flour, sugar, salt and butter to a food processor and pulse until sandy.</step>
            <step>Add water and pulse until it comes together. Add a small amount more water only if needed.</step>
            <step>Place dough on counter. With the palm of the hand, push small quantities of the dough outward to smear together the ingredients further.</step>
			<step>Form into a cohesive disk and refrigerate until firm, at least <time>30 minutes</time>.</step>
			<step>Preheat oven to <temperature>375</temperature>.</step>
            <step>Roll out pastry and line a <equipment>9-inch by 2-inch tart pan</equipment>. Set pan on a <equipment>baking sheet</equipment>.</step>
			<step>Line shell with foil and weight with beans or pie weights. <procedure>Blind-bake</procedure> until set but not browned, about <time>12 minutes</time>.</step>
            <step>Remove from oven and cool, but leave oven on.</step>
		</steps>
	</group>
	<group>
		<label>Apples</label>
		<ingredients>
            <ingredient>
                <quantity>
                    <value>450</value>
                    <unit>g</unit>
                </quantity>
                <variant>sweet</variant>
                <item>apples</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>75</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/3</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>sugar</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>1</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/2</value>
                            <unit>tsp</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>cinnamon</item>
                <preprep>ground</preprep>
            </ingredient>
		</ingredients>
        <steps>
            <step>Peel and core the apples.</step>
            <step>Slice the apples lengthwise 1/2 cm thick.</step>
            <step>Toss the apples together with sugar and cinnamon.</step>
            <step>Arrange the apples decoratively in concentric rings in the tart crust.</step>
            <step>Return to the oven and bake <time>20 minutes</time>, until they are almost tender.</step>
            <step>Remove from oven and cool, but leave oven on.</step>
        </steps>
	</group>
    <group>
        <label>Custard</label>
        <ingredients>
            <ingredient>
                <quantity>
                    <value>1</value>
                </quantity>
                <item>egg</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>75</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/3</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>sugar</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>30</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/4</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <variant>all-purpose</variant>
                <item>flour</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>115</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>1/2</value>
                            <unit>cup</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <variant>35%</variant>
                <item>cream</item>
            </ingredient>
            <ingredient>
                <quantity>
                    <value>40</value>
                    <unit>g</unit>
                    <altmeasure>
                        <quantity>
                            <value>3</value>
                            <unit>tbs</unit>
                        </quantity>
                    </altmeasure>
                </quantity>
                <item>Calvados</item>
            </ingredient>
            <ingredient>
                <item>confectioners' sugar</item>
            </ingredient>
        </ingredients>
        <steps>
            <step>Combine egg and sugar. Beat until light, about <time>5 minutes</time>.</step>
            <step>Beat in the flour, then the cream, then the Calvados.</step>
            <step>Pour custard over the apples in the crust. Fill almost to the top of the shell but be careful not to overflow.</step>
            <step>Return to the oven and bake until the custard begins to puff, about <time>10 minutes</time>.</step>
            <step>Remove from oven but leave oven on. Sprinkle tart heavily and evenly with confectioners' sugar.</step>
            <step>Return to the oven and bake until well browned and set, about <time>15 minutes</time> to <time>20 minutes</time> more.</step>
        </steps>
    </group>
    <serving>Serve warm. Can be reheated.</serving>
</recipe>

=== michael-n-cooper/recipes/source/stollen.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Stollen</title>
	<meta>
		<cuisine>German</cuisine>
		<dishtype>Cakes</dishtype>
		<dishtype>Breads</dishtype>
		<occasion>Christmas</occasion>
	</meta>
	<group>
		<label>Fruit mixture</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>170</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>candied citrus peel</item>
				<note>Use any mix of orange, lemon, and citron. Beware of colourful "mixed peels" whose primary ingredient is actually rutabaga. (!)</note>
			</ingredient>
			<ingredient>
				<quantity>
					<value>170</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>raisins</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>115</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/2</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>brandy</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>15</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1</value>
							<unit>tbs</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>orange extract</item>
			</ingredient>
		</ingredients>
		<steps>
			<step>Combine all ingredients in a bowl and cover.</step>
			<step>Let fruit absorb liquid for <time>2 days</time>, stirring occasionally. The fruit will absorb nearly all of it.</step>
		</steps>
	</group>
	<group>
		<label>Sponge</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>150</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2/3</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>milk</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>90</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>bread</variant>
				<item>flour</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>8</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>osmotolerant</variant>
				<item>yeast</item>
				<note>If you don't have osmotolerant yeast, double the rising times (except for the sponge phase).</note>
			</ingredient>
		</ingredients>
		<steps>
			<step>Combine ingredients in a stand mixer fitted with the paddle blade. Mix together until well developed, <time>5 minutes</time>.</step>
			<step>Cover, put in a warm spot and <procedure>proof</procedure> for <time>1 hour</time>.</step>
		</steps>
	</group>
	<group>
		<label>Dough</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>175</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>butter</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>30</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>tbs</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>sugar</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>5</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>salt</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>4</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>vanilla extract</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>30</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>tbs</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item><reciperef ref="almond-paste">almond paste</reciperef></item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>260</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>cups</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>bread</variant>
				<item>flour</item>
			</ingredient>
		</ingredients>
		<steps>
			<step>Still in the stand mixer with the paddle attachment, add all ingredients to the sponge except flour above and mix until smoothly combined.</step>
			<step>Add the flour. Mix to knead the dough extremely well, about <time>30 minutes</time>. Dough should form a satiny smooth mass.</step>
			<step>Cover, put in a warm spot, and <procedure>proof</procedure> again until doubled, about <time>1 hour</time>.</step>
		</steps>
	</group>
	<group>
		<label>Shaping</label>
		<ingredients>
			<ingredient mainingredient="true">
				<quantity>
					<value>175</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2/3</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item><reciperef ref="almond-paste">almond paste</reciperef></item>
			</ingredient>
		</ingredients>
		<steps>
			<step>Drain the residual liquid well from the dried fruits and retain.</step>
			<step>Roll out the dough and spread the drained fruits over it. Fold the dough over and gently knead in the fruits just until evenly dispersed.</step>
			<step>Let dough rest <time>10 minutes</time>. Meanwhile, divide the almond paste in half and roll each half into a log about 9 inches long.</step>
			<step>Divide the dough in two pieces. Roll each piece to a 10 x 10 inch square, making it thin in the middle and thicker on the two edges.</step>
			<step>Place a log of almond paste in the thin section. Fold over one thick edge and place on top of the almond paste, beside the other thick edge, so the thin section fully wraps around the almond paste. The cake should now have two sides that are about equally thick, and a mound in the centre. Seal all the dough edges.</step>
			<step>Grease a <equipment>baking sheet</equipment> or line with parchment paper. Transfer the cakes to the sheet, spaced somewhat apart. Cover with plastic or a kitchen towel. Let rise about <time>1 1/2 hours</time>, until it grows to at least one and half times in size.</step>
			<step>Preheat the oven to <temperature>350</temperature>. Bake about <time>30 minutes</time> until mahogany brown.</step>
		</steps>
	</group>
	<group>
		<label>Finishing</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>113</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/2</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>butter</item>
			</ingredient>
			<ingredient>
				<item>reserved liquor from fruits</item>
			</ingredient>
			<ingredient>
				<variant>confectioner's</variant>
				<item>sugar</item>
			</ingredient>
		</ingredients>
		<steps>
			<step>While the cakes bake, <procedure>clarify</procedure> the butter.</step>
			<step>When cakes are done, remove to a wire rack. Brush immediately all over with the reserved fruit liquor, then brush immediately all over with the clarified butter.</step>
			<step>Let cool completely, then dust well in confectioner's sugar.</step>
			<step>Leave out overnight to dry slightly.</step>
			<step>Place in airtight plastic and let mellow at room temperature up to one month.</step>
		</steps>
	</group>
</recipe>

=== michael-n-cooper/recipes/source/ground-salt.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Ground Salt</title>
	<meta>
		<comment>This finely ground salt is useful when regular salt would not dissolve fully, such as hot candy mixtures, and to season popcorn and nuts. This salt will clump so should be resifted just before use.</comment>
	</meta>
	<ingredients>
		<ingredient>
			<item>salt</item>
			<note>Use salt with no additives such as flow agents.</note>
		</ingredient>
	</ingredients>
	<steps>
		<step>Grind salt well in a clean <equipment>spice mill</equipment>.</step>
		<step><procedure>Sift</procedure> salt through a <equipment>fine strainer</equipment>. Regrind or discard the portion that does not pass through the strainer.</step>
	</steps>
	<storage>Store in an airtight container.</storage>
</recipe>

=== michael-n-cooper/recipes/source/buchedenoel.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Bûche de Noël</title>
	<meta>
		<dishtype>Desserts</dishtype>
		<dishtype>Cakes</dishtype>
	</meta>
	<ingredients>
		<ingredient>
			<quantity>
				<value>1</value>
			</quantity>
			<item><reciperef ref="spongecake">sponge cake, prepared for jelly roll</reciperef></item>
		</ingredient>
		<ingredient>
			<quantity>
				<value>1 1/2</value>
				<unit>cups</unit>
			</quantity>
			<item><reciperef ref="pastrycream">pastry cream, prepared for cake filling</reciperef></item>
		</ingredient>
		<ingredient>
			<quantity approximate="true">
				<value>1</value>
				<unit>cup</unit>
			</quantity>
			<item><reciperef ref="ganachefrosting">ganache frosting</reciperef></item>
		</ingredient>
	</ingredients>
	<steps>
		<step>Prepare sponge cake as for a jelly roll.</step>
		<step>Fill roll cake with pastry cream and re-roll.</step>
		<step>Place cake on a serving platter. Cut off a few inches of both ends. Stand one of the end on top of the cake, cut side up, to represent a protruding branch. The other end is cook's treat.</step>
		<step>Ice cake with the ganache frosting, but leave all cut ends exposed to represent wood. Run tines of a fork along the frosting to represent tree bark.</step>
		<step>Decorate as desired with marzipan or meringue mushrooms, leaves, pine cones, etc.</step>
	</steps>
	<serving>Just before serving, sift a fine dusting of powdered sugar over the cake to represent snow.</serving>
</recipe>

=== michael-n-cooper/recipes/source/raised-coffee-cake.en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "../recipes.dtd">
<recipe>
	<title>Raised Coffee Cake</title>
	<meta>
		<source>Marion Cunningham: The Fannie Farmer Cookbook, 13th Edition (1994: Knopf) (adapted)</source>
		<dishtype>Breakfast</dishtype>
		<occasion>Sunday Brunch</occasion>
		<comment>Raised coffee cake is the most refined version. Although it is yeast-raised like bread, the recipe forms a batter instead of a dough. The extensible batter becomes very airy during the rising process. The poolish gives a more complex flavour to the cake that really makes it, but it can be skipped; simply add the poolish ingredients with the other cake ingredients.</comment>
	</meta>
	<group>
		<label>Poolish</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>100</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/2</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>water</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>100</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>all purpose</variant>
				<item>flour</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>.2</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/16</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>instant</variant>
				<item>yeast</item>
			</ingredient>
		</ingredients>
		<steps>
			<step>Stir ingredients well to make a smooth batter.</step>
			<step>Cover and let rise overnight, <time>8 - 10 hours</time>.</step>
		</steps>
	</group>
	<group>
		<label>Cake</label>
		<ingredients>
			<ingredient>
				<quantity>
					<value>170</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>3/4</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>milk</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>115</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
						</quantity>
					</altmeasure>
				</quantity>
				<item>eggs</item>
			</ingredient>
			<ingredient>
				<item>poolish</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>100</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/2</value>
							<unit>cup</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>sugar</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>200</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1 2/3</value>
							<unit>cups</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>all purpose</variant>
				<item>flour</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>3</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>1/2</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>salt</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value>8</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>tsp</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<variant>instant</variant>
				<item>yeast</item>
			</ingredient>
			<ingredient>
				<quantity>
					<value></value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>5</value>
							<unit>tbs</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item>butter</item>
				<preprep>softened</preprep>
			</ingredient>
			<ingredient>
				<quantity>
					<value>300</value>
					<unit>g</unit>
					<altmeasure>
						<quantity>
							<value>2</value>
							<unit>cups</unit>
						</quantity>
					</altmeasure>
				</quantity>
				<item><reciperef ref="streusel">streusel</reciperef></item>
			</ingredient>
		</ingredients>
		<steps>
			<step><procedure>Scald</procedure> the milk and cool to room temperature. Bring butter and eggs to room temperature.</step>
			<step>Add all ingredients except butter to the poolish.</step>
			<step><procedure>Beat</procedure> together well <time>5 minutes</time>, using the paddle attachment if using a stand mixer. This will form a smooth and elastic batter.</step>
			<step>Add the butter and beat in until fully incorporated.</step>
			<step>Cover and set aside to rise until double in bulk, about <time>2 hours</time>.</step>
			<step>Grease well a <equipment>9-inch tube pan</equipment>.</step>
			<step>Stir down the dough until fully collapsed. Spread about half of it in the tube pan. Sprinkle with about 2/3 of the streusel, then cover with the remaining dough.</step>
			<step>Stir streusel and batter together very slighly, only one movement per section of the cake, to streak the streusel through the cake without blending it in.</step>
			<step>Sprinkle the remaining streusel over the top of the cake.</step>
			<step>Cover and set aside to raise until double again, about <time>1 hour</time>.</step>
			<step><time>15 minutes before rising is done, preheat oven to </time> <temperature>350</temperature>.</step>
			<step>Bake for about <time>45 minutes</time>, until brown and done inside.</step>
			<step>Cool on a rack in the pan, then remove from pan.</step>
		</steps>
	</group>
</recipe>
